services:
  db:
    image: postgres:15.14-alpine3.21
    environment:
      POSTGRES_DB: fileApp
      POSTGRES_USER: fileApp_user
      POSTGRES_PASSWORD: fileApp_pass
    ports:
      - "54210:5432"
    healthcheck:
      test: [CMD-SHELL, pg_isready -U cli_user -d cli_pass]
      interval: 5s
      timeout: 3s
      retries: 20