spring:
  application:
    name: transaction-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:39092,localhost:49092}
    admin:
      fail-fast: true
  datasource:
    url: jdbc:postgresql://localhost:5436/transaction
    hikari:
      schema: transaction
      username: transaction
      password: transaction
  flyway:
    url: jdbc:postgresql://localhost:5436/transaction
    user: transaction
    password: transaction
    baseline-on-migrate: true
server:
  port: 8092

logging:
  level:
    org.apache.kafka.clients: INFO
    org.springframework.kafka: INFO

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  otlp:
#    metrics:
#      export:
#        url: http://localhost:4318/v1/metrics
#        step: 5s
#  opentelemetry:
#    tracing:
#      export:
#        otlp:
#          transport: grpc
#          endpoint: http://localhost:4317
#    logging:
#      export:
#        otlp:
#          transport: grpc
#          endpoint: http://localhost:4317