# Логическая база данных (имя)
databaseName: shardingsphere_db

dataSources:
  # Источники данных: мастеры и реплики для двух шардов
  shard0_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://transaction-service-postgres-shard-1:5432/transaction
    username: transaction
    password: transaction
  shard1_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://transaction-service-postgres-shard-2:5432/transaction
    username: transaction
    password: transaction

rules:
  - !READWRITE_SPLITTING
    dataSources:
      shard0:  # логический источник данных для шарда0 с репликацией
        writeDataSourceName: shard0_master
        readDataSourceNames: [shard0_master]
        loadBalancerName: round_robin   # алгоритм балансировки между репликами
      shard1:
        writeDataSourceName: shard1_master
        readDataSourceNames: [shard1_master]
        loadBalancerName: round_robin
    loadBalancers:
      round_robin:
        type: ROUND_ROBIN

  - !SHARDING
    tables:
      order_tbl:                     # имя логической таблицы
        actualDataNodes: shard${0..1}.wallets
        tableStrategy:
          standard:
            shardingColumn: uid
            shardingAlgorithmName: uid_hash_algo
        databaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: uid_db_hash_algo
#    bindingTables: [ order_tbl, order_item_tbl ]  # пример связки (если две таблицы шардиируются совместно)
    defaultDataSource: shard0  # куда отправлять данные без шардирования (необязательно)
    shardingAlgorithms:
      uid_db_hash_algo:
        type: INLINE
        props:
          algorithm-expression: shard${uid % 2}    # user_id mod 2 -> shard0 или shard1
      uid_hash_algo:
        type: INLINE
        props:
          algorithm-expression: order_tbl_${uid % 2}  # order_id mod 2 -> суффикс таблицы