hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:54210/cli
hibernate.connection.username=cli_user
hibernate.connection.password=cli_pass
hibernate.show_sql=false
hibernate.format_sql=true
hibernate.connection.autocommit=false