spring:
  application:
    name: module-2.5
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/changeme
    username: changeme
    password: changeme
    name: changeme
  flyway:
    url: jdbc:postgresql://localhost:5432/changeme
    user: changeme
    password: changeme
    locations: classpath:db/migration
    clean-disabled: false

jwt:
  secret: h7tllLhLRIi3j2DSp7ogR47RacuJ5cMGawgnwfLpXim
  expiration: 3600
  issuer: tmq

aws:
  url: http://localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin12345
  bucket: back

logging:
  level:
    com.tmq: debug