spring:
  application:
    name: module-2.5
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/app
    username: app
    password: app
  flyway:
    url: jdbc:postgresql://localhost:5432/app
    user: app
    password: app
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true


jwt:
  secret: h7tllLhLRIi3j2DSp7ogR47RacuJ5cMGawgnwfLpXim
  expiration: 3600
  issuer: tmq

aws:
  url: http://localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin12345
  bucket: back

logging:
  level:
    com.tmq: debug

