hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:54210/fileApp
hibernate.connection.username=fileApp_user
hibernate.connection.password=fileApp_pass
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.connection.autocommit=false
file.path=/home/tmq/apache-tomcat-11.0.13/uploads/