hibernate.connection.driver_class=${hibernate.connection.driver_class}
hibernate.connection.url=${datasource.url}
hibernate.connection.username=${datasource.user}
hibernate.connection.password=${datasource.password}
hibernate.show_sql=${hibernate.show_sql}
hibernate.format_sql=${hibernate.format_sql}
hibernate.connection.autocommit=${hibernate.connection.autocommit}
file.path=${file.path}
jwt.token=${jwt.token}
flyway.migrations.path=${flyway.migrations.path}

