plugins {
	id "java"
	id "org.springframework.boot" version "${springBootVersion}"
	id "io.spring.dependency-management" version "${springDependencyManagementVersion}"
	id "org.openapi.generator" version "${openApiGeneratorVersion}"
	id "maven-publish"
}

group = 'com.tmq'
version = '1.0.0'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	//spring
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.kafka:spring-kafka'
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	//database
	implementation "org.postgresql:postgresql:${postgresDriverVersion}"
	implementation 'org.flywaydb:flyway-core:12.4.0'
	runtimeOnly 'org.flywaydb:flyway-database-postgresql:12.4.0'
//	implementation 'org.apache.shardingsphere:shardingsphere-jdbc:5.5.3'
//	implementation 'org.apache.shardingsphere:shardingsphere-infra-url-classpath:5.5.3'

	//observability
	runtimeOnly 'io.micrometer:micrometer-registry-otlp'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:${otlpLogbackAppenderVersion}"
	implementation 'io.micrometer:micrometer-tracing-bridge-otel'
	runtimeOnly 'io.opentelemetry:opentelemetry-exporter-otlp'
	implementation 'io.projectreactor:reactor-core-micrometer'

	//helpers
	implementation 'org.jspecify:jspecify:1.0.0'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation "org.mapstruct:mapstruct:${mapstructVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

	// open api
	implementation "io.swagger.core.v3:swagger-annotations:${swaggerAnnotationsVersion}"
	implementation "io.swagger.core.v3:swagger-models:${swaggerModelsVersion}"
	implementation "jakarta.validation:jakarta.validation-api:${jakartaValidationApiVersion}"
	implementation "org.openapitools:jackson-databind-nullable:${jacksonDatabindNullableVersion}"
	compileOnly "jakarta.servlet:jakarta.servlet-api:${jakartaServletApiVersion}"

	//test
	testImplementation 'org.springframework.kafka:spring-kafka-test'
}

openApiGenerate {
	generatorName.set("spring")
	inputSpec.set("$projectDir/openapi/transaction-service.yaml")
	outputDir.set("$buildDir/generated/openapi")
	apiPackage.set("com.tmq.person.service.api")
	modelPackage.set("com.tmq.person.service.dto")
	configOptions = [
			"library": "spring-cloud",
			"useSpringBoot4": "true",
			"useBeanValidation" : "true",
			"openApiNullable" : "true",
			"skipDefaultInterface": "true",
			"useFeignClientUrl" : "true"]
}

sourceSets {
	main {
		java.srcDir("$buildDir/generated/openapi/src/main/java")
		resources.srcDir("$buildDir/generated/openapi/src/main/resources")
	}

	test {
		java.srcDir("$buildDir/generated/openapi/src/test/java")
		resources.srcDir("$buildDir/generated/openapi/src/test/resources")
	}
}

tasks.named('processResources') {
	dependsOn('openApiGenerate')
}

tasks.named('processTestResources') {
	dependsOn('openApiGenerate')
}

tasks.named('compileJava') {
	dependsOn('openApiGenerate')
}



publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
	repositories {
		maven {
			name = "nexus"
			def nexusHost = System.getenv("NEXUS_URL") ?: "http://localhost:9081"
			def nexusUsername = System.getenv("NEXUS_USERNAME") ?: "admin"
			def nexusPassword = System.getenv("NEXUS_PASSWORD") ?: "admin"
			url = version.endsWith("SNAPSHOT")
					? "${nexusHost}/repository/maven-snapshots/"
					: "${nexusHost}/repository/maven-releases/"
			allowInsecureProtocol = true
			credentials {
				username = nexusUsername
				password = nexusPassword
			}
		}
	}
}
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('bootJar') {
	requiresUnpack '**/shardingsphere*.jar'
}
