INSERT INTO person.countries (name, created, updated, status) VALUES
    ('Afghanistan', NOW(), NOW(), 'ACTIVE'),
    ('Albania', NOW(), NOW(), 'ACTIVE'),
    ('Algeria', NOW(), NOW(), 'ACTIVE'),
    ('Andorra', NOW(), NOW(), 'ACTIVE'),
    ('Angola', NOW(), NOW(), 'ACTIVE'),
    ('Antigua and Barbuda', NOW(), NOW(), 'ACTIVE'),
    ('Argentina', NOW(), NOW(), 'ACTIVE'),
    ('Armenia', NOW(), NOW(), 'ACTIVE'),
    ('Australia', NOW(), NOW(), 'ACTIVE'),
    ('Austria', NOW(), NOW(), 'ACTIVE'),
    ('Azerbaijan', NOW(), NOW(), 'ACTIVE'),
    ('Bahamas', NOW(), NOW(), 'ACTIVE'),
    ('Bahrain', NOW(), NOW(), 'ACTIVE'),
    ('Bangladesh', NOW(), NOW(), 'ACTIVE'),
    ('Barbados', NOW(), NOW(), 'ACTIVE'),
    ('Belarus', NOW(), NOW(), 'ACTIVE'),
    ('Belgium', NOW(), NOW(), 'ACTIVE'),
    ('Belize', NOW(), NOW(), 'ACTIVE'),
    ('Benin', NOW(), NOW(), 'ACTIVE'),
    ('Bhutan', NOW(), NOW(), 'ACTIVE'),
    ('Bolivia', NOW(), NOW(), 'ACTIVE'),
    ('Bosnia and Herzegovina', NOW(), NOW(), 'ACTIVE'),
    ('Botswana', NOW(), NOW(), 'ACTIVE'),
    ('Brazil', NOW(), NOW(), 'ACTIVE'),
    ('Brunei', NOW(), NOW(), 'ACTIVE'),
    ('Bulgaria', NOW(), NOW(), 'ACTIVE'),
    ('Burkina Faso', NOW(), NOW(), 'ACTIVE'),
    ('Burundi', NOW(), NOW(), 'ACTIVE'),
    ('Cabo Verde', NOW(), NOW(), 'ACTIVE'),
    ('Cambodia', NOW(), NOW(), 'ACTIVE'),
    ('Cameroon', NOW(), NOW(), 'ACTIVE'),
    ('Canada', NOW(), NOW(), 'ACTIVE'),
    ('Central African Republic', NOW(), NOW(), 'ACTIVE'),
    ('Chad', NOW(), NOW(), 'ACTIVE'),
    ('Chile', NOW(), NOW(), 'ACTIVE'),
    ('China', NOW(), NOW(), 'ACTIVE'),
    ('Colombia', NOW(), NOW(), 'ACTIVE'),
    ('Comoros', NOW(), NOW(), 'ACTIVE'),
    ('Congo', NOW(), NOW(), 'ACTIVE'),
    ('Costa Rica', NOW(), NOW(), 'ACTIVE'),
    ('Croatia', NOW(), NOW(), 'ACTIVE'),
    ('Cuba', NOW(), NOW(), 'ACTIVE'),
    ('Cyprus', NOW(), NOW(), 'ACTIVE'),
    ('Czech Republic', NOW(), NOW(), 'ACTIVE'),
    ('Denmark', NOW(), NOW(), 'ACTIVE'),
    ('Djibouti', NOW(), NOW(), 'ACTIVE'),
    ('Dominica', NOW(), NOW(), 'ACTIVE'),
    ('Dominican Republic', NOW(), NOW(), 'ACTIVE'),
    ('Ecuador', NOW(), NOW(), 'ACTIVE'),
    ('Egypt', NOW(), NOW(), 'ACTIVE'),
    ('El Salvador', NOW(), NOW(), 'ACTIVE'),
    ('Equatorial Guinea', NOW(), NOW(), 'ACTIVE'),
    ('Eritrea', NOW(), NOW(), 'ACTIVE'),
    ('Estonia', NOW(), NOW(), 'ACTIVE'),
    ('Eswatini', NOW(), NOW(), 'ACTIVE'),
    ('Ethiopia', NOW(), NOW(), 'ACTIVE'),
    ('Fiji', NOW(), NOW(), 'ACTIVE'),
    ('Finland', NOW(), NOW(), 'ACTIVE'),
    ('France', NOW(), NOW(), 'ACTIVE'),
    ('Gabon', NOW(), NOW(), 'ACTIVE'),
    ('Gambia', NOW(), NOW(), 'ACTIVE'),
    ('Georgia', NOW(), NOW(), 'ACTIVE'),
    ('Germany', NOW(), NOW(), 'ACTIVE'),
    ('Ghana', NOW(), NOW(), 'ACTIVE'),
    ('Greece', NOW(), NOW(), 'ACTIVE'),
    ('Grenada', NOW(), NOW(), 'ACTIVE'),
    ('Guatemala', NOW(), NOW(), 'ACTIVE'),
    ('Guinea', NOW(), NOW(), 'ACTIVE'),
    ('Guinea-Bissau', NOW(), NOW(), 'ACTIVE'),
    ('Guyana', NOW(), NOW(), 'ACTIVE'),
    ('Haiti', NOW(), NOW(), 'ACTIVE'),
    ('Honduras', NOW(), NOW(), 'ACTIVE'),
    ('Hungary', NOW(), NOW(), 'ACTIVE'),
    ('Iceland', NOW(), NOW(), 'ACTIVE'),
    ('India', NOW(), NOW(), 'ACTIVE'),
    ('Indonesia', NOW(), NOW(), 'ACTIVE'),
    ('Iran', NOW(), NOW(), 'ACTIVE'),
    ('Iraq', NOW(), NOW(), 'ACTIVE'),
    ('Ireland', NOW(), NOW(), 'ACTIVE'),
    ('Israel', NOW(), NOW(), 'ACTIVE'),
    ('Italy', NOW(), NOW(), 'ACTIVE'),
    ('Jamaica', NOW(), NOW(), 'ACTIVE'),
    ('Japan', NOW(), NOW(), 'ACTIVE'),
    ('Jordan', NOW(), NOW(), 'ACTIVE'),
    ('Kazakhstan', NOW(), NOW(), 'ACTIVE'),
    ('Kenya', NOW(), NOW(), 'ACTIVE'),
    ('Kiribati', NOW(), NOW(), 'ACTIVE'),
    ('Kuwait', NOW(), NOW(), 'ACTIVE'),
    ('Kyrgyzstan', NOW(), NOW(), 'ACTIVE'),
    ('Laos', NOW(), NOW(), 'ACTIVE'),
    ('Latvia', NOW(), NOW(), 'ACTIVE'),
    ('Lebanon', NOW(), NOW(), 'ACTIVE'),
    ('Lesotho', NOW(), NOW(), 'ACTIVE'),
    ('Liberia', NOW(), NOW(), 'ACTIVE'),
    ('Libya', NOW(), NOW(), 'ACTIVE'),
    ('Liechtenstein', NOW(), NOW(), 'ACTIVE'),
    ('Lithuania', NOW(), NOW(), 'ACTIVE'),
    ('Luxembourg', NOW(), NOW(), 'ACTIVE'),
    ('Madagascar', NOW(), NOW(), 'ACTIVE'),
    ('Malawi', NOW(), NOW(), 'ACTIVE'),
    ('Malaysia', NOW(), NOW(), 'ACTIVE'),
    ('Maldives', NOW(), NOW(), 'ACTIVE'),
    ('Mali', NOW(), NOW(), 'ACTIVE'),
    ('Malta', NOW(), NOW(), 'ACTIVE'),
    ('Marshall Islands', NOW(), NOW(), 'ACTIVE'),
    ('Mauritania', NOW(), NOW(), 'ACTIVE'),
    ('Mauritius', NOW(), NOW(), 'ACTIVE'),
    ('Mexico', NOW(), NOW(), 'ACTIVE'),
    ('Micronesia', NOW(), NOW(), 'ACTIVE'),
    ('Moldova', NOW(), NOW(), 'ACTIVE'),
    ('Monaco', NOW(), NOW(), 'ACTIVE'),
    ('Mongolia', NOW(), NOW(), 'ACTIVE'),
    ('Montenegro', NOW(), NOW(), 'ACTIVE'),
    ('Morocco', NOW(), NOW(), 'ACTIVE'),
    ('Mozambique', NOW(), NOW(), 'ACTIVE'),
    ('Myanmar', NOW(), NOW(), 'ACTIVE'),
    ('Namibia', NOW(), NOW(), 'ACTIVE'),
    ('Nauru', NOW(), NOW(), 'ACTIVE'),
    ('Nepal', NOW(), NOW(), 'ACTIVE'),
    ('Netherlands', NOW(), NOW(), 'ACTIVE'),
    ('New Zealand', NOW(), NOW(), 'ACTIVE'),
    ('Nicaragua', NOW(), NOW(), 'ACTIVE'),
    ('Niger', NOW(), NOW(), 'ACTIVE'),
    ('Nigeria', NOW(), NOW(), 'ACTIVE'),
    ('North Korea', NOW(), NOW(), 'ACTIVE'),
    ('North Macedonia', NOW(), NOW(), 'ACTIVE'),
    ('Norway', NOW(), NOW(), 'ACTIVE'),
    ('Oman', NOW(), NOW(), 'ACTIVE'),
    ('Pakistan', NOW(), NOW(), 'ACTIVE'),
    ('Palau', NOW(), NOW(), 'ACTIVE'),
    ('Palestine', NOW(), NOW(), 'ACTIVE'),
    ('Panama', NOW(), NOW(), 'ACTIVE'),
    ('Papua New Guinea', NOW(), NOW(), 'ACTIVE'),
    ('Paraguay', NOW(), NOW(), 'ACTIVE'),
    ('Peru', NOW(), NOW(), 'ACTIVE'),
    ('Philippines', NOW(), NOW(), 'ACTIVE'),
    ('Poland', NOW(), NOW(), 'ACTIVE'),
    ('Portugal', NOW(), NOW(), 'ACTIVE'),
    ('Qatar', NOW(), NOW(), 'ACTIVE'),
    ('Romania', NOW(), NOW(), 'ACTIVE'),
    ('Russia', NOW(), NOW(), 'ACTIVE'),
    ('Rwanda', NOW(), NOW(), 'ACTIVE'),
    ('Saint Kitts and Nevis', NOW(), NOW(), 'ACTIVE'),
    ('Saint Lucia', NOW(), NOW(), 'ACTIVE'),
    ('Saint Vincent and the Grenadines', NOW(), NOW(), 'ACTIVE'),
    ('Samoa', NOW(), NOW(), 'ACTIVE'),
    ('San Marino', NOW(), NOW(), 'ACTIVE'),
    ('Sao Tome and Principe', NOW(), NOW(), 'ACTIVE'),
    ('Saudi Arabia', NOW(), NOW(), 'ACTIVE'),
    ('Senegal', NOW(), NOW(), 'ACTIVE'),
    ('Serbia', NOW(), NOW(), 'ACTIVE'),
    ('Seychelles', NOW(), NOW(), 'ACTIVE'),
    ('Sierra Leone', NOW(), NOW(), 'ACTIVE'),
    ('Singapore', NOW(), NOW(), 'ACTIVE'),
    ('Slovakia', NOW(), NOW(), 'ACTIVE'),
    ('Slovenia', NOW(), NOW(), 'ACTIVE'),
    ('Solomon Islands', NOW(), NOW(), 'ACTIVE'),
    ('Somalia', NOW(), NOW(), 'ACTIVE'),
    ('South Africa', NOW(), NOW(), 'ACTIVE'),
    ('South Korea', NOW(), NOW(), 'ACTIVE'),
    ('South Sudan', NOW(), NOW(), 'ACTIVE'),
    ('Spain', NOW(), NOW(), 'ACTIVE'),
    ('Sri Lanka', NOW(), NOW(), 'ACTIVE'),
    ('Sudan', NOW(), NOW(), 'ACTIVE'),
    ('Suriname', NOW(), NOW(), 'ACTIVE'),
    ('Sweden', NOW(), NOW(), 'ACTIVE'),
    ('Switzerland', NOW(), NOW(), 'ACTIVE'),
    ('Syria', NOW(), NOW(), 'ACTIVE'),
    ('Taiwan', NOW(), NOW(), 'ACTIVE'),
    ('Tajikistan', NOW(), NOW(), 'ACTIVE'),
    ('Tanzania', NOW(), NOW(), 'ACTIVE'),
    ('Thailand', NOW(), NOW(), 'ACTIVE'),
    ('Timor-Leste', NOW(), NOW(), 'ACTIVE'),
    ('Togo', NOW(), NOW(), 'ACTIVE'),
    ('Tonga', NOW(), NOW(), 'ACTIVE'),
    ('Trinidad and Tobago', NOW(), NOW(), 'ACTIVE'),
    ('Tunisia', NOW(), NOW(), 'ACTIVE'),
    ('Turkey', NOW(), NOW(), 'ACTIVE'),
    ('Turkmenistan', NOW(), NOW(), 'ACTIVE'),
    ('Tuvalu', NOW(), NOW(), 'ACTIVE'),
    ('Uganda', NOW(), NOW(), 'ACTIVE'),
    ('Ukraine', NOW(), NOW(), 'ACTIVE'),
    ('United Arab Emirates', NOW(), NOW(), 'ACTIVE'),
    ('United Kingdom', NOW(), NOW(), 'ACTIVE'),
    ('United States', NOW(), NOW(), 'ACTIVE'),
    ('Uruguay', NOW(), NOW(), 'ACTIVE'),
    ('Uzbekistan', NOW(), NOW(), 'ACTIVE'),
    ('Vanuatu', NOW(), NOW(), 'ACTIVE'),
    ('Vatican City', NOW(), NOW(), 'ACTIVE'),
    ('Venezuela', NOW(), NOW(), 'ACTIVE'),
    ('Vietnam', NOW(), NOW(), 'ACTIVE'),
    ('Yemen', NOW(), NOW(), 'ACTIVE'),
    ('Zambia', NOW(), NOW(), 'ACTIVE'),
    ('Zimbabwe', NOW(), NOW(), 'ACTIVE');