plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
    id 'org.openapi.generator' version "${openApiGeneratorVersion}"
}

apply plugin: 'org.openapi.generator'

group = 'com.tmq'
version = '1.0.0'
description = 'REST API для регистрации, логина, обновления токена и получения информации о пользователе через Keycloak.'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // common
    implementation 'com.tmq:common:1.0.0'

    //spring web + data
    implementation 'org.springframework.boot:spring-boot-starter-webclient'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    //security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'

    //observability
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.25.0-alpha'
    implementation 'io.micrometer:context-propagation:1.2.1'
    implementation 'io.github.openfeign:feign-micrometer'

    //aop
    implementation 'org.springframework.boot:spring-boot-starter-aop:4.0.0-M2'

    //reactor micrometer bridge
    implementation 'io.projectreactor:reactor-core-micrometer'

    //helpers
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //test
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webclient-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation "com.github.dasniko:testcontainers-keycloak:${testcontainersKeycloakVersion}"
    testImplementation 'org.wiremock:wiremock-standalone:3.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // OPEN API
    implementation "io.swagger.core.v3:swagger-annotations:${swaggerAnnotationsVersion}"
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
