FROM gradle:9.3.1-jdk25 AS build
WORKDIR /home/gradle/project
COPY build.gradle .
COPY gradle.properties .
COPY src ./src
COPY openapi ./openapi

RUN gradle --no-daemon clean bootJar

FROM eclipse-temurin:25

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /home/gradle/project/build/libs/*.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]