spring:
  application:
    name: individuals-api

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: individuals-api
            client-secret: 6Y26alesiYGdlaGafX5QXSS8Yx76LV6R
            client-name: individuals-api
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/payment-system
            token-uri: http://localhost:8080/realms/payment-system/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
server:
  port: 8085


keycloak:
  url: http://localhost
  port: 8080

management:
  metrics:
    tags:
      application: individuals-api
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: prometheus
