spring:
  application:
    name: individuals-api

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: individuals-api
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            client-name: individuals-api
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/payment-system
            token-uri: ${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/payment-system/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/payment-system
server:
  port: 8090

keycloak:
  url: ${KEYCLOAK_HOST}
  port: ${KEYCLOAK_PORT}
